### ISSUE TITLE
这个报错是什么原因

### ISSUE THREAD

**Issue by duoshoumiao** [watermellye/AutoPCR_Archived#1]
![Screenshot_2024-02-08-23-28-15-60_c8caf204774d15df9c96f9997a2407c4.jpg](https://github.com/watermellye/AutoPCR_Archived/assets/94856184/26e69dd2-ef39-4057-887b-e6454ee285b9)

**Comment by duoshoumiao** [comment]
![Screenshot_2024-02-09-00-54-00-05_c8caf204774d15df9c96f9997a2407c4.jpg](https://github.com/watermellye/AutoPCR_Archived/assets/94856184/bff9999e-f60d-48ab-990d-9b75c85f8bd1)

我只能尝试联系一下你

**Comment by duoshoumiao** [comment]
怎么激活农场

**Comment by watermellye** [comment]
这个是因为之前PCR有一次更新以后，登录相关的API发生了一次变化，但我没有将这个变动上传到repo中，不好意思。
你把/check/check_agreement这一行删掉试试。
我过年的时候会更新一波整个AuotPCR并上传。

**Comment by duoshoumiao** [comment]
> 这个是因为之前PCR有一次更新以后，登录相关的API发生了一次变化，但我没有将这个变动上传到repo中，不好意思。
> 你把/check/check_agreement这一行删掉试试。
> 我过年的时候会更新一波整个AuotPCR并上传。

👌

**Comment by watermellye** [comment]
我已打开fork后的项目的issue栏。这里的我会关闭。
如需联系，可以进ep群 770828442
